# This is a basic workflow to help you get started with Actions

name: verify

on:
  - push
  - pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        uses: actions/cache@v2.1.2
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: node_modules/*
          # An explicit key for restoring and saving the cache
          key: PAP_NODE_MODULES
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn --frozen-lockfile
      - run: yarn lint
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        uses: actions/cache@v2.1.2
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: node_modules/*
          # An explicit key for restoring and saving the cache
          key: PAP_NODE_MODULES
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn --frozen-lockfile
      - run: yarn test:e2e:ci
